sudo: required
dist: trusty
language: android
node_js:
    4.2.3
android:
    components:
        - platform-tools
        - tools
        - build-tools-23.0.2
        - android-19
        - extra-android-support
        - extra-android-m2repository
        - sys-img-armeabi-v7a-android-19

before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
    - wget http://dl.google.com/android/ndk/android-ndk-$NDK_VERSION-linux-x86_64.bin
    - chmod +x android-ndk-$NDK_VERSION-linux-x86_64.bin
    - "./android-ndk-$NDK_VERSION-linux-x86_64.bin | egrep -v ^Extracting"
    - export ANDROID_NDK_HOME=`pwd`/android-ndk-$NDK_VERSION
    - export PATH=${PATH}:${ANDROID_NDK_HOME}

before_script:
    - npm install -g grunt-cli
    - npm install
    - echo no | android create avd --force -n Arm19 -t android-19 -b armeabi-v7a -c 12M
    - emulator -avd Arm19 -no-skin -no-audio -no-window &
    - android-wait-for-emulator
script:
    - grunt default
    - node --version
    - npm --version
    - npm install nativescript -g
    - grunt buildOnlyTestsApp --platform=Android --modulesPath=./bin/dist/tns-core-modules-1.7.0.tgz --emuPId=.*emulator.* --avd=Api19 --showEmu=false
    - grunt runOnlyTestsApp --platform=Android --modulesPath=./bin/dist/tns-core-modules-1.7.0.tgz --emuPId=.*emulator.* --avd=Api19 --showEmu=false

