sudo: required
dist: trusty
language: android
node_js:
    4.2.3
android:
    components:
        - platform-tools
        - tools
        - build-tools-23.0.2
        - android-19
        - extra-android-support
        - extra-android-m2repository
        - sys-img-armeabi-v7a-android-19
before_script:
    - npm install -g grunt-cli
    - npm install
script:
    grunt default

